// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvjtK5tL0IF8dLutz98PuIxmfQ0ir4HI',
    appId: '1:53080880315:web:3dcc9fc6ed72206d66259e',
    messagingSenderId: '53080880315',
    projectId: 'auth-truco',
    authDomain: 'auth-truco.firebaseapp.com',
    storageBucket: 'auth-truco.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJfrnfldk1_6p44PM2lE8qvuMK0mFWunE',
    appId: '1:53080880315:android:8e2ec2ec565a7fce66259e',
    messagingSenderId: '53080880315',
    projectId: 'auth-truco',
    storageBucket: 'auth-truco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbeJ1rGxUyonZDzHMWURbTzEkwCQDnLo8',
    appId: '1:53080880315:ios:6648e04259be6b1966259e',
    messagingSenderId: '53080880315',
    projectId: 'auth-truco',
    storageBucket: 'auth-truco.appspot.com',
    iosBundleId: 'com.example.trucoNato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbeJ1rGxUyonZDzHMWURbTzEkwCQDnLo8',
    appId: '1:53080880315:ios:4398442f7c05eb4366259e',
    messagingSenderId: '53080880315',
    projectId: 'auth-truco',
    storageBucket: 'auth-truco.appspot.com',
    iosBundleId: 'com.example.trucoNato.RunnerTests',
  );
}
